# ROS2 Parameters
/**:
    ros__parameters:
        device_port: "/dev/ttyUSB-U2D2"
        baud_rate: 1000000
        control_topic: "/dynamixel_control"
        status_topic: "/dynamixel_status"
        dynamixels:
            ids: [0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] # 16개
            types: ["MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX", "MX"] # 16개
            max_position_limits: [3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159, 3.14159]
            min_position_limits: [-3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159, -3.14159]
